### ISSUE TITLE
Amazing project ! I seem to be getting some errors here ...

### ISSUE THREAD

**Issue by animemandir** [onderonur/next-moviez#2]
Hi, would greatly appreciate if you can help me here...

- I am using `pnpm` package manager.
- made only small changes to the project like - change name in package.json and APP_TITLE.

![image](https://user-images.githubusercontent.com/78192713/160331395-d7ff814f-d22e-4af1-b5c7-0f1a69413336.png)

Please tell what is wrong here.

**Comment by onderonur** [comment]
First of all, thank you!

Actually, there is nothing wrong. That is just a warning by Next.js which says the project is using `getInitialProps` in `pages/_app` and because of that it can not run some optimization features. It's a trade off of using `getInitialProps` of `App` component.
