### ISSUE TITLE
Warning: You have opted-out of Automatic Static Optimization due to `getInitialProps` in `pages/_app`. This does not opt-out pages with `getStaticProps`

### ISSUE THREAD

**Issue by arvi9** [onderonur/next-moviez#4]
Warning: You have opted-out of Automatic Static Optimization due to `getInitialProps` in `pages/_app`. This does not opt-out pages with `getStaticProps`.
I got this message when i build nextjs App. Code [https://github.com/onderonur/tmdb-explorer/blob/master/src/pages/_app.tsx](https://github.com/onderonur/tmdb-explorer/blob/master/src/pages/_app.tsx)

**Comment by onderonur** [comment]
Closing this since the repository will be migrated to the Next.js App Router and won't support Pages Router anymore.
